---
- hosts: all
  become: yes
  vars:
    user: user
    shell: /usr/bin/zsh

  pre_tasks:
    - name: Enable multilib
      community.general.xbps:
        name:
          - void-repo-multilib
          - void-repo-multilib-nonfree

  roles:
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: development, tags: development }
    - { role: flatpak, tags: flatpak }
    # - { role: runit, tags: runit }
    - { role: power, tags: power }
    - { role: virtualization, tags: virtualization }
    - { role: containers, tags: containers }
    # - { role: zram, tags: zram }
    - { role: acpi, tags: acpi }
    - { role: bluetooth, tags: bluetooth }
    # TODO
    # - { role: gpdwin2, tags: gpdwin2 }
    # - { role: plymouth, tags: plymouth }
    # - firewall?
    # - sdkman ?
