---
- hosts: all
  become: yes
  vars:
    user: user
    shell: /usr/bin/zsh
    home_path: '/home/{{ user }}'
    apply_gpdwin2_config: false
    apply_kde_config: false
    install_flatpaks: false
    install_virtualization: false
    install_containers: false
    install_kde_apps: false
    install_xfce_apps: false

  pre_tasks:
    - name: Upgrade xbps
      community.general.xbps:
          upgrade_xbps: true

    - name: Upgrade system
      community.general.xbps:
          upgrade: true

    - name: Enable multilib and nonfree
      community.general.xbps:
        name:
          - void-repo-multilib
          - void-repo-multilib-nonfree
          - void-repo-nonfree

  roles:
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: development, tags: development }
    - { role: flatpak, tags: flatpak, when: install_flatpaks }
    - { role: runit, tags: runit }
    - { role: power, tags: power }
    - { role: virtualization, tags: virtualization, when: install_virtualization }
    - { role: containers, tags: containers, when: install_containers }
    - { role: zram, tags: zram }
    - { role: acpi, tags: acpi }
    - { role: bluetooth, tags: bluetooth }
    - { role: gpdwin2, tags: gpdwin2, when: apply_gpdwin2_config }
    - { role: kde-plasma, tags: kde-plasma, when: apply_kde_config  }
