---
- name: install desktop packages
  community.general.xbps:
    name: '{{ item }}'
  loop:
    # DE
    - xorg-server-xwayland # xorg backend for wayland
    - wl-clipboard # clipboard manager
    - xdg-desktop-portal-wlr # screen sharing for wayland
    - xdg-desktop-portal-gtk # fallback portal
    - xdg-user-dirs
    - xdg-utils
    - kdesu
    - kdegraphics-thumbnailers
    - ffmpegthumbs
    - power-profiles-daemon
    - nerd-fonts-ttf
    - noto-fonts-ttf # unicode font
    - noto-fonts-emoji # emojis
    - dejavu-fonts-ttf # fonts
    - font-awesome5 # Icon font
    - font-awesome6 # Icon font
    - onedrive
    # Video
    - mesa # DRI 3D acceleration
    - mesa-dri # DRI 3D acceleration
    - mesa-demos # glxgears command
    - intel-media-driver # intel driver iHD
    - libva-utils # hardware video acceleration
    # Graphical apps
    - mpv # video player
    - vlc # video player
    - youtube-dl
    - ark # KDE archiver
    - okular # pdf editor, no img
    - spectacle # screenshots utility
    - nomacs # image viewer
    - filelight # disk usage analyzer
    - strawberry # audio player
    - milkytracker # fast tracker clone
    - keepassxc # password manager
