---
- name: install desktop packages
  community.general.xbps:
    name: '{{ item }}'
    update_cache: false
  loop:
    # DE
    - wl-clipboard # clipboard manager
    - kdesu
    - kdegraphics-thumbnailers
    - ffmpegthumbs
    - noto-fonts-ttf # unicode font
    - noto-fonts-emoji # emojis
    - dejavu-fonts-ttf # fonts
    - font-awesome5 # Icon font
    - font-awesome6 # Icon font
    - onedrive
    - plasma-workspace-wallpapers
    - dolphin-plugins
    # Video
    - mesa # DRI 3D acceleration
    - mesa-dri # DRI 3D acceleration
    - mesa-demos # glxgears command
    - intel-media-driver # intel driver iHD
    - libva-utils # hardware video acceleration
    # Graphical apps
    - mpv # video player
    - vlc # video player
    - youtube-dl
    - ark # KDE archiver
    - okular # pdf editor, no img
    - spectacle # screenshots utility
    - nomacs # image viewer
    - filelight # disk usage analyzer
    - strawberry # audio player
    - milkytracker # fast tracker clone
    - keepassxc # password manager
    - plasma-firewall # ufw gui

- name: install power-profiles-daemon
  community.general.xbps:
    name: power-profiles-daemon
    update_cache: false
  notify: restart power-profiles-daemon
