---
- name: install fisher
  become: true
  become_user: '{{ user }}'
  shell: 'fish -c curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'

- name: install tide prompt
  become: true
  become_user: '{{ user }}'
  shell: 'fish -c fisher install IlanCosman/tide@v6'

- name: install sdkman for fish
  become: true
  become_user: '{{ user }}'
  shell: 'fish -c fisher install reitzig/sdkman-for-fish@v2.1.0'
