---
- name: install some games and gaming related utilities
  community.general.xbps:
    name: '{{ item }}'
    update_cache: false
  loop:
    - nethack
    - gzdoom
    - bsd-games
    - gamemode
    - lutris
