---
- name: include tasks
  include_tasks:
    file: '{{ desktop_task_item }}.yml'
    apply:
      tags: '{{ desktop_task_item }}'
  tags: always
  loop:
    - desktop
    - steam
    - games
    - plymouth
