#SPDX-License-Identifier: MIT-0
---

- name: plasma - kdeglobals
  become: true
  become_user: '{{ user }}'
  community.general.ini_file:
    path: '{{ home_path }}/.config/kdeglobals'
    section: KDE
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
    mode: 0600
  loop:
  - option: AnimationDurationFactor
    value: 0.125
  - option: SingleClick
    value: true

- name: plasma - baloo
  become: true
  become_user: '{{ user }}'
  community.general.ini_file:
    path: '{{ home_path }}/.config/baloofilerc'
    section: Basic Settings
    option: Indexing-Enabled
    value: 'false'
    no_extra_spaces: yes
    mode: 0600

- name: plasma - konsole
  become: true
  become_user: '{{ user }}'
  community.general.ini_file:
    path: '{{ home_path }}/.config/konsolerc'
    section: Desktop Entry
    option: DefaultProfile
    value: Fish.profile
    no_extra_spaces: yes
    mode: 0600

- name: plasma - add konsole profile
  become: true
  become_user: '{{ user }}'
  copy:
    force: yes
    dest: '{{ home_path }}/.local/share/konsole/Fish.profile'
    content: |
      [Appearance]
      Font=0xProto Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1

      [General]
      Command=/usr/bin/fish
      Name=Fish
      Parent=FALLBACK/

- name: plasma - krunner
  become: true
  become_user: '{{ user }}'
  community.general.ini_file:
    path: '{{ home_path }}/.config/krunnerrc'
    section: Plugins
    option: baloosearchEnabled
    value: false
    no_extra_spaces: false
    mode: 0600

- name: plasma - plasmashellrc
  become: true
  become_user: '{{ user }}'
  community.general.ini_file:
    path: '{{ home_path }}/.config/plasmashellrc'
    section: 'PlasmaViews][Panel 2'
    no_extra_spaces: false
    mode: 0600
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  loop:
  - option: floating
    value: 0
  - option: panelOpacity
    value: 1

- name: plasma - plasma-org.kde.plasma.desktop-appletsrc
  become: true
  become_user: '{{ user }}'
  community.general.ini_file:
    path: '{{ home_path }}/.config/plasma-org.kde.plasma.desktop-appletsrc'
    section: 'Containments][2][Applets][18][Configuration][Appearance'
    no_extra_spaces: false
    mode: 0600
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  loop:
  - option: dateFormat
    value: isoDate
  - option: use24hFormat
    value: 2
