---
- name: install flatpak
  community.general.xbps:
    name: flatpak

- name: Add the flathub flatpak repo
  become: true
  become_user: '{{ user }}'
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    method: user
    flatpakrepo_url: "{{ item.repo }}"
  loop:
    - { name: 'flathub', repo: 'https://dl.flathub.org/repo/flathub.flatpakrepo' }

- name: Install flatpak packages
  become: true
  become_user: '{{ user }}'
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    remote: flathub
    method: user
  loop:
    - rocks.koreader.KOReader
#    - io.github.flattool.Warehouse
    - com.vysp3r.ProtonPlus
    - com.heroicgameslauncher.hgl
    # - it.mijorus.gearlever
    - org.dupot.easyflatpak
    - com.github.tchx84.Flatseal
    - org.fedoraproject.MediaWriter
    - io.github.getnf.embellish
#    - org.gnome.Boxes
