#SPDX-License-Identifier: MIT-0
---
- name: install development tools
  community.general.xbps:
    name: '{{ item }}'
    update_cache: false
  loop:
    # C/C++
    - gdb
    - cmake
    - cmake-extras
    - meson
    - ninja
    - clang
    - clang-tools-extra
    - clang-analyzer
    - lld
    - llvm
    - ctags
    - gcc
    - libstdc++-devel
    - automake
    - heaptrack
    - hotspot
    - cpp-utilities
    - cppcheck
    # Python
    - uv
    - python3-pip
    - python3-pipenv
    - python3-devel
    # Lua
    - lua
    - luarocks
    # Java
    - openjdk17
    - openjdk21
    # Rust
    - rust
    - rust-doc
    - rustup
    - cargo
    # Node
    - nodejs

- name: install sdkman
  become: true
  become_user: '{{ user }}'
  shell: 'curl -s "https://get.sdkman.io" | bash'

- name: install groovy with sdkman
  become: true
  become_user: '{{ user }}'
  shell: 'bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install groovyserv && sdk install groovy"'

- name: configure GROOVY_HOME in fish
  become: true
  become_user: '{{ user }}'
  shell: >
    fish -c "set -U GROOVY_HOME /home/{{ user }}/.sdkman/candidates/groovy/current"

- name: configure GROOVY_HOME in zsh
  become: true
  become_user: '{{ user }}'
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    marker: "### GROOVY_HOME ###"
    insertbefore: "#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!"
    block: "export GROOVY_HOME=/home/{{ user }}/.sdkman/candidates/groovy/current"

- name: configure EDITOR in fish
  become: true
  become_user: '{{ user }}'
  shell: >
    fish -c "set -U EDITOR nvim"

- name: configure EDITOR in zsh
  become: true
  become_user: '{{ user }}'
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    marker: "### EDITOR ###"
    insertbefore: "#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!"
    block: "export EDITOR=nvim"
