#SPDX-License-Identifier: MIT-0
---
- name: install development tools
  community.general.xbps:
    name: '{{ item }}'
    update_cache: false
  loop:
    # C/C++
    - gdb
    - cmake
    - cmake-extras
    - ninja
    - clang
    - clang-tools-extra
    - clang-analyzer
    - lld
    - llvm
    - ctags
    - gcc
    - libstdc++-devel
    - make
    - automake
    - autoconf
    # Python
    - uv
    - python3-pip
    - python3-pipenv
    - python3-devel
    # Lua
    - lua
    - LuaJIT
    - luarocks
    # Java
    - openjdk17
    - openjdk21
    # Rust
    - rust
    - rust-doc
    - rustup
    - cargo
    # Node
    - nodejs
