#SPDX-License-Identifier: MIT-0
---
- name: install intel-undervolt
  community.general.xbps:
    name: intel-undervolt

- name: configure intel-undervolt CPU
  lineinfile:
    path: /etc/intel-undervolt.conf
    line: "undervolt 0 'CPU' 90"
    search_string: "undervolt 0 'CPU' 0"

- name: configure intel-undervolt GPU
  lineinfile:
    path: /etc/intel-undervolt.conf
    line: "undervolt 0 'GPU' 90"
    search_string: "undervolt 0 'GPU' 0"

- name: configure intel-undervolt power package
  lineinfile:
    path: /etc/intel-undervolt.conf
    line: "power package 5/5 2/30"
    insert_after: "# Example: power package 45/0.002:disabled 35/28:enabled"

- name: check if it is required to upgdate grub for GPD Win 2
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*fbcon=rotate'
    state: absent
  check_mode: true
  register: grub_cmdline_gpdwin2_check
  changed_when: false

- name: update grub config file for GPD Win 2 P1
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: '\1 fbcon=rotate:1 video=eDP-1:panel_orientation=right_side_up"'
  when: grub_cmdline_gpdwin2_check.found == 0

- name: update grub config file for GPD Win 2 P2
  shell: echo 'GRUB_GFXMODE=720x1280x32' >> /etc/default/grub
  when: grub_cmdline_gpdwin2_check.found == 0

- name: configure grub
  shell: update-grub
  when: grub_cmdline_gpdwin2_check.found == 0
