---
- name: install ufw
  community.general.xbps:
    name: ufw
    update_cache: true
  notify: restart ufw

- name: install irqbalance
  community.general.xbps:
    name: irqbalance

- name: restart irqbalance
  community.general.runit:
    name: irqbalance
    enabled: yes
    state: restarted

- name: install packages
  community.general.xbps:
    name: '{{item}}'
    update_cache: false
  loop:
    # Shell
    - fish-shell # powerful shell
    - zsh
    - bc # maths
    - jq # json processor
    - bat # colorized cat
    - fzf # fuzzy finder
    - ripgrep # search tool
    - ripgrep-all
    - fd # find tool
    - the_silver_searcher # code searching tool
    - neovim # future of vim
    - python3-neovim
    - neovide
    - neovim-qt
    - delta # git pager
    - tree-sitter-devel
    - tree
    - tmux # terminal multiplexer
    - python3-tmuxp # tmux session manager
    - yazi
    - lazygit # git tui
    # System
    - xtools # helpers for working with XBPS
    - xmirror # easily select xbps mirror
    - htop # system monitor
    - btop # system monitor
    - net-tools # netstat
    - mtr # ping/traceroute diag tool
    - fwupd # dell firmware updater
    - irqbalance
    - nmap # port scanner
    - tcpdump # packet analyzer
    - whois # query registry
    - vsv # list runit services
    # Disk
    - iotop # disk "top"
    - ncdu # disk usage analyzer
    - smartmontools # S.M.A.R.T Monitoring Tools
    # Network
    - nethogs # net "top"
    - openssh
    - sshpass # allow ansible -k
    - sshuttle # vpn through ssh
    - keychain # ssh-agent wrapper
    - wget # downloader
    - bind-utils # dns tools
    - openbsd-netcat # network utility
    # Utils
    - at # scheduler
    - rsync # sync tool
    - rclone # sync tool
    - zip
    - unzip # uncompress zip
    - zstd
    - 7zip
    - bzip2
    - gcal
    - units
    - cifs-utils
    - ipcalc # ipv4 network calculator
    - pv # progress bar
    - lzop # compression tool
    - hyperfine # like time

- name: Configure root
  user:
    name: root
    shell: '{{shell}}'

- name: Configure user
  user:
    name: '{{user}}'
    shell: '{{shell}}'

- name: add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '{{ ansible_hostname }}'
    line: '127.0.0.1               {{ ansible_hostname }}'
    state: present

- name: do not ask for password with sudo for wheel members
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
